name: easy_inputs
description: Common FormzInputs representations using Formz Package
repository: https://github.com/Avila-Tek/easy_inputs
issue_tracker: https://github.com/Avila-Tek/easy_inputs/issues
homepage: https://github.com/Avila-Tek/easy_inputs
documentation: https://github.com/Avila-Tek/easy_inputs

version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  formz: ^0.6.0
  intl: ^0.18.1
  
dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.0
  very_good_analysis: ^3.1.0
