name: easy_inputs
description: Common FormzInputs representations using Formz Package
repository: https://https://github.com/Avila-Tek/formz_representation
issue_tracker: https://https://github.com/Avila-Tek/formz_representation/issues
homepage: https://https://github.com/Avila-Tek/formz_representation
documentation: https://https://github.com/Avila-Tek/formz_representation

version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  formz: ^0.6.0
  intl: ^0.18.1
  
dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.0
  very_good_analysis: ^3.1.0
